server:
  port: 8080
  error:
    include-message: ALWAYS

spring:
  profiles:
    active: dev
    default: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: ms-users

eureka:
  client:
    enabled: true
    register-with-eureka: true

application.version: @project.version@

springdoc:
  swagger-ui:
    path: "/api/users/swagger/swagger-ui.html"
  api-docs:
    path: "/api/users/v3/api-docs"