server:
  port: 8080
  error:
    include-message: ALWAYS

spring:
  datasource:
    url: jdbc:h2:file:~/Documents/Codes/Java/Spring Boot/training/H2_Storage/users
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: ALWAYS

springdoc:
  swagger-ui:
    path: "/api/users/swagger/swagger-ui.html"
  api-docs:
    path: "/api/users/v3/api-docs"