spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservices
    username: chakarai1234
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"