spring:
  profiles:
    active: dev
    default: dev
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: USERS

eureka:
  client:
    enabled: true
    register-with-eureka: true

application.version: @project.version@
header-missing-value: "Required Headers are missing (x-correleation-id & Country)"